// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGzK0XKXaIa6JWtbg4kOFa9Xbh6e9I6mA',
    appId: '1:411737693537:web:097ee5cb3a8b4459183920',
    messagingSenderId: '411737693537',
    projectId: 'fittracker-75339',
    authDomain: 'fittracker-75339.firebaseapp.com',
    storageBucket: 'fittracker-75339.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJevtNBKbGffF0_UkMnOgf9szInmaKggU',
    appId: '1:411737693537:android:302ca655412385b7183920',
    messagingSenderId: '411737693537',
    projectId: 'fittracker-75339',
    storageBucket: 'fittracker-75339.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYHnSGGxPKsEZRS6A6xL78CmlfTT1Cb_I',
    appId: '1:411737693537:ios:da4d25ad82ebe7a4183920',
    messagingSenderId: '411737693537',
    projectId: 'fittracker-75339',
    storageBucket: 'fittracker-75339.appspot.com',
    androidClientId: '411737693537-7vcrpck45il509kfq6hhejpsdio9mtrs.apps.googleusercontent.com',
    iosClientId: '411737693537-2em28tivoi9j58jdg6ngdi7il9ilc5us.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYHnSGGxPKsEZRS6A6xL78CmlfTT1Cb_I',
    appId: '1:411737693537:ios:da4d25ad82ebe7a4183920',
    messagingSenderId: '411737693537',
    projectId: 'fittracker-75339',
    storageBucket: 'fittracker-75339.appspot.com',
    androidClientId: '411737693537-7vcrpck45il509kfq6hhejpsdio9mtrs.apps.googleusercontent.com',
    iosClientId: '411737693537-2em28tivoi9j58jdg6ngdi7il9ilc5us.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitTracker',
  );
}
